AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs14.x
    Properties:
      LayerName: "accelerate-bug-shared"
      ContentUri: shared/
      CompatibleRuntimes:
        - nodejs14.x

  SayHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 1024
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Layers:
        - !Ref SharedLayer
      CodeUri: say-hello/
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /say-hello
            Method: get
